version: '3.8'

services: 
  
  web:
    build: .
    image: books
    volumes: 
      - .:/code
    ports:
      - 8000:8000
    env_file: 
      - .env/web.env
    command: python /code/manage.py runserver 0.0.0.0:8000
    depends_on: 
      - db
  
  db:
    image: postgres
    env_file: 
      - ./.env/db.env
    volumes:
      - django-books:/var/lib/postgresql/data

volumes: 
  django-books:
    external: true
    name: django-books