version: '3.8'

services: 
  
  web:
    build: .
    image: books
    volumes: 
      - .:/code
    ports:
      - 8000:8000
    env_file: 
      - .env/web-prod.env
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
    depends_on: 
      - db
  
  db:
    image: postgres
    env_file: 
      - ./.env/db.env
