version: '3.8'

services: 
  
  web:
    build: .
    image: books
    volumes: 
      - .:/code
    ports:
      - 8000:8000
    env_file: 
      - .env/web.env
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
    depends_on: 
      - db
  
  db:
    image: postgres
    env_file: 
      - ./.env/db.env
    volumes:
      - books_postgres_data:/var/lib/postgresql/data

volumes: 
  books_postgres_data:
    external: true
    name: books_postgres_data